apiVersion: v1
kind: Template
metadata:
  name: nuxt-s2i-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nuxt-app
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: nuxt-build
  spec:
    source:
      git:
        uri: <專案的 Git 位址>
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:latest
    output:
      to:
        kind: ImageStreamTag
        name: nuxt-app:latest
  triggers:
    - type: GitHub
      github:
        secret: <GitHub Webhook Secret>
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nuxt-deployment
  spec:
    replicas: 1
    selector:
      app: nuxt-app
    template:
      metadata:
        labels:
          app: nuxt-app
      spec:
        containers:
          - name: nuxt-container
            image: nuxt-app:latest
            ports:
              - containerPort: 3000
            command:
              - "/bin/sh"
              - "-c"
            args:
              - |
                npm install &&
                npm run dev