apiVersion: v1
kind: BuildConfig
metadata:
  name: nuxt-build
spec:
  source:
    git:
      uri: https://github.com/wanyutang/ocp-nuxt3-demo.git
      ref: main
      contextDir: package
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:latest
  output:
    to:
      kind: ImageStreamTag
      name: nuxt-app:latest
triggers:
  - type: GitHub
    github:
      secret: githubcomwanyutangocpnuxt3demo
