apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: demo-app
    app.kubernetes.io/component: demo-app
    app.kubernetes.io/instance: demo-app
  name: demo-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: demo-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: package
    git:
      uri: https://github.com/wanyutang/ocp-nuxt3-demo
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: node:14
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 5kAMsQbwm0pl4XVf7M_k
    type: GitHub
  - generic:
      secret: U7lYo-DBO92v7TDghIqn
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
