apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    controller.devfile.io/devworkspace-source: web-terminal
    controller.devfile.io/restricted-access: "true"
    controller.devfile.io/started-at: "1685322340571"
  finalizers:
  - rbac.controller.devfile.io
  labels:
    console.openshift.io/terminal: "true"
    controller.devfile.io/creator: 70f81ec8-4b78-4efe-916e-0f933434f395
  name: terminal-im9s3y
spec:
  routingClass: web-terminal
  started: true
  template:
    components:
    - name: web-terminal-tooling
      plugin:
        kubernetes:
          name: web-terminal-tooling
          namespace: crw
    - name: web-terminal-exec
      plugin:
        kubernetes:
          name: web-terminal-exec
          namespace: crw
