apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"v1","kind":"ResourceQuota","metadata":{"labels":{"toolchain.dev.openshift.com/owner":"wanyutang","toolchain.dev.openshift.com/provider":"codeready-toolchain"},"name":"compute-deploy","namespace":"wanyutang-dev"},"spec":{"hard":{"limits.cpu":"20000m","limits.memory":"14Gi","requests.cpu":"3000m","requests.memory":"14Gi"},"scopes":["NotTerminating"]}}'
  labels:
    toolchain.dev.openshift.com/owner: wanyutang
    toolchain.dev.openshift.com/provider: codeready-toolchain
  name: compute-deploy
spec:
  hard:
    limits.cpu: "20"
    limits.memory: 14Gi
    requests.cpu: "3"
    requests.memory: 14Gi
  scopes:
  - NotTerminating
