apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-workspaces
    app.kubernetes.io/part-of: devworkspace-operator
    controller.devfile.io/workspace-rbac: "true"
  name: devworkspace-default-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devworkspace-default-role
subjects:
- kind: ServiceAccount
  name: workspaceed6274a6a0e74506-sa
  namespace: wanyutang-dev
