apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-workspaces
    app.kubernetes.io/part-of: devworkspace-operator
    controller.devfile.io/workspace-rbac: "true"
  name: devworkspace-default-rolebinding
roleRef:
  name: devworkspace-default-role
  namespace: wanyutang-dev
subjects:
- kind: ServiceAccount
  name: workspaceed6274a6a0e74506-sa
  namespace: wanyutang-dev
userNames:
- system:serviceaccount:wanyutang-dev:workspaceed6274a6a0e74506-sa
